---
title: "Journalist Visualizations"
author: "Jackson Callaghan"
date: "3/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library import, include=False}
suppressMessages(library(tidyverse))
suppressMessages(library(fiftystater))
suppressMessages(library(viridis))
suppressMessages(library(scales))
suppressMessages(library(sf))
suppressMessages(library(albersusa))
suppressMessages(library(maptools))
suppressMessages(library(sp))
library(usmap)
library(RColorBrewer)
```


```{r message=FALSE, warning=FALSE}
ufo_us <- read_csv('../Data/ufo_data_us_cleaned_v2.csv') %>% 
  mutate(Posted = as.Date(Posted, format = "%m/%d/%y")) %>% 
  mutate(`Date/Time` = as.Date(`Date/Time`, format = "%m/%d/%y %H:%M")) %>% 
  mutate(State = tolower(state.name[match(State, state.abb)])) %>% 
  filter(`Date/Time` < as.Date('2021-03-24'))

ufo_non_us <- read_csv('../Data/ufo_data_non_us_cleaned_v2.csv') %>% 
  mutate(Posted = as.Date(Posted, format = "%m/%d/%y")) %>% 
  mutate(`Date/Time` = as.Date(`Date.Time`, format = "%m/%d/%y %H:%M")) %>% 
  mutate(State = tolower(state.name[match(State, state.abb)])) %>% 
  filter(`Date/Time` < as.Date('2021-03-24'))

routes_data <- read_csv('../Data/routes.csv')
airport_data <- read.csv('../Data/airports.csv', stringsAsFactors = FALSE)
```



```{r}
ufo_us_coords <- ufo_us %>% 
  dplyr::select(lng, lat, 0:7) %>% 
  usmap_transform() %>% 
  dplyr::select(-lng, -lat) %>% 
  rename(lng = lng.1, lat = lat.1)
```

```{r}
data("fifty_states")

year.range <- c(2000, 2021)

ufo_us_freq <- ufo_us_coords %>% 
  filter(
    parse_integer(format(`Date.Time`, "%Y")) >= year.range[1] &
    parse_integer(format(`Date.Time`, "%Y")) <= year.range[2]
  ) %>% 
  group_by(State) %>% 
  summarise(freq = n()) %>% 
  drop_na()

bg.color <- "white"

ufo_us_freq <- ufo_us_freq %>% 
  mutate(state = State)
plot_usmap(data = ufo_us_freq, values = "freq") +
  scale_fill_viridis_c(
    limits = c(0, max(ufo_us_freq$freq, na.rm = TRUE)),
    name = "Frequency",
    option = "viridis"
  ) +
  guides(fill = guide_legend()) +
  labs(
    title = paste(
      "Number of reported UFO Sightings by State, ",
      format(year.range[1]),
      "-", format(year.range[2])
    )
  ) +
  theme_void() +
  theme(
    plot.background = element_rect(fill = bg.color, color = bg.color),
    legend.margin = margin(20, 20, 20, 20),
    plot.title = element_text(hjust = 0.5)
  )
```

Need a good sense of what the upper bound should be. (This isn't part of the prototype)

```{r}
qt <- quantile(ufo_us$Duration, na.rm = TRUE, probs = c(.5, .75, .8, .9, 1))

print(qt)

ufo_us %>% 
  filter(Duration < mean(c(qt[[1]], qt[[2]]))) %>% 
ggplot() +
  geom_density(aes(x = Duration))
```


```{r}
timescale <- 60 * 60

cutoff <- ufo_us %>% 
  mutate(Duration = Duration / timescale) %>% 
  pull(Duration)

cutoff <- quantile(cutoff, .99, na.rm = TRUE)[[1]]

year.range = c(2020, 2021)

bg.color <- "#323232"
fg.color <- "#121212"
border.color <- "#222222"
text.color <- "light gray"

plot_usmap(fill = fg.color, color = border.color) +
  geom_point(
    data = ufo_us_coords %>% 
      filter(!is.na(Duration)) %>% 
      mutate(Duration = Duration / timescale) %>% 
      filter(Duration <= cutoff) %>% 
      filter(
        parse_integer(format(`Date.Time`, "%Y")) >= year.range[1] &
        parse_integer(format(`Date.Time`, "%Y")) <= year.range[2]
      ) %>% 
      arrange(Duration), 
    aes(x = lng, y = lat, color = Duration), 
    alpha = 1
  ) +
  scale_color_viridis_c(
    option = 'viridis', 
    limits = c(0, cutoff),
    na.value = fg.color,
  ) +
  # guides(color = guide_legend()) +
  labs(
    title = paste(
      "Individual UFO reports by Sighting Duration in Hours, ",
      format(year.range[1]),
      "-", format(year.range[2])
    )
  ) +
  theme_void() +
  theme(
    plot.background = element_rect(fill = bg.color),
    legend.background = element_rect(fill = bg.color, color = bg.color),
    plot.title = element_text(color = text.color, hjust = 0.5),
    legend.text = element_text(color = text.color),
    legend.title = element_text(color = text.color),
    legend.margin = margin(20, 20, 20, 20)
  )
```

```{r}
# cutoff <- mean(c(qt[[1]], qt[[2]]))
# cutoff <- 20000

year.range <- c(1969, 2021)

bg.color <- "#323232"
fg.color <- "#121212"
border.color <- "#222222"
text.color <- "light gray"

by.city <- ufo_us_coords %>% 
  filter(
    parse_integer(format(Date.Time, "%Y")) >= year.range[1] &
    parse_integer(format(Date.Time, "%Y")) <= year.range[2]
  ) %>% 
  mutate(year = parse_integer(format(Date.Time, "%Y"))) %>% 
  group_by(lat, lng) %>% 
  summarise(freq = n(), city = first(city_lower), .groups = "keep")

cutoff <- quantile(by.city$freq, .99)[[1]]

plot_usmap(fill = fg.color, color = border.color) +
  geom_point(
    data = by.city %>% arrange(freq) %>% filter(freq <= cutoff),
    aes(x = lng, y = lat, color = freq), 
    alpha = 1
  ) +
  scale_color_viridis_c(
    option = 'plasma', 
    limits = c(0, cutoff),
    na.value = fg.color,
    name = "Frequency"
  ) +
  geom_point(
    data = by.city %>% arrange(freq) %>% filter(freq > cutoff),
    aes(x = lng, y = lat),
    color = "white"
  ) +
  # scale_color_manual(
  #   name = "> 65 Reports"
  # ) +
  labs(
    title = paste(
      "UFO Report Frequency by City Location, ",
      format(year.range[1]),
      "-", format(year.range[2])
    ),
    caption = "Note: white dots (1% of cities) have >65 reports, ranging 66-479."
  ) +
  theme_void() +
  theme(
    plot.background = element_rect(fill = bg.color),
    legend.background = element_rect(fill = bg.color, color = bg.color),
    plot.title = element_text(color = text.color, hjust = 0.5),
    legend.text = element_text(color = text.color),
    legend.title = element_text(color = text.color),
    legend.margin = margin(20, 20, 20, 20),
    plot.caption = element_text(color = text.color, hjust = 0.5)
  )
```


```{r}

year.range <- c(1969, 2021)

ufo_us %>% 
  filter(
    parse_integer(format(`Date/Time`, "%Y")) > year.range[1] &
    parse_integer(format(`Date/Time`, "%Y")) < year.range[2]
  ) %>% 
  mutate(year = parse_integer(format(`Date/Time`, "%Y"))) %>% 
  group_by(year) %>% 
  summarise(freq = n()) %>% 
  drop_na() %>% 
  ggplot() +
    geom_line(aes(x = year, y = freq), size = 1)
```

A bar chart of ufo shapes

```{r}
ufo_us %>% 
  mutate(Shape = ifelse(is.na(Shape), "Unknown", Shape)) %>%
  group_by(Shape) %>% 
  summarize(freq = n()) %>%
  ggplot() +
    geom_bar(aes(x = reorder(Shape, -freq), y = freq), stat = "identity") +
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
    labs(y = "Frequency", x = "UFO Shape")
    
```

A density plot of duration 

```{r}
qt <- quantile(ufo_us$Duration, na.rm = TRUE, probs = c(.5, .75, .8, .9, 1))


ufo_us %>% 
  filter(Duration < quantile(Duration, .5, na.rm = TRUE)[[1]]) %>% 
  mutate(Duration = Duration / 60) %>% 
ggplot() +
  geom_density(aes(x = Duration), size = 1) +
  scale_x_continuous(breaks = seq(0, 11, by = 1))
```

```{r}
ufo_us %>% 
  filter(Duration > quantile(Duration, .99, na.rm = TRUE)[[1]]) %>% 
ggplot() +
  geom_density(aes(x = Duration), size = 1)
```
